import type { LaunchFormState, ProtocolMetrics, TokenPool } from "./types";

export const LAUNCH_FEE_ETH = 0.0005;
export const BASE_FEE_BPS = 100;
export const CREATOR_SHARE_BPS = 7000;
export const PROTOCOL_SHARE_BPS = 3000;
export const MAX_CREATOR_TAX_BPS = 500;

export const DEFAULT_LAUNCH_STATE: LaunchFormState = {
  name: "",
  ticker: "",
  description: "",
  twitter: "",
  telegram: "",
  website: "",
  imagePreview: null,
  hookMode: "master",
  customHookAddress: "",
  modules: {
    antiSnipe: true,
    antiSnipeDuration: 5,
    antiSnipeInitialTax: 99,
    backedFloor: true,
    floorAllocation: 10,
    antiMev: true,
    maxWallet: false,
    maxWalletBps: 200,
    maxTx: false,
    maxTxBps: 100,
  },
  creatorTaxBps: 50,
  devBuyEth: "",
  quoteAsset: "ETH",
};

export const MOCK_METRICS: ProtocolMetrics = {
  totalVolume: 12_847_392,
  floorLockedEth: 284.7,
  totalPools: 142,
};

export const MOCK_POOLS: TokenPool[] = [
  {
    id: "1",
    name: "Programmable",
    ticker: "V4",
    image: "",
    banner: "",
    bannerGradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
    marketCap: 526_000,
    floorValue: 42_000,
    liquidity: 210_000,
    change24h: 12.4,
    hooks: { antiSnipe: true, backedFloor: true, antiMev: false, customHook: false },
    address: "0x7987...24EE",
    hookType: "Master",
  },
  {
    id: "2",
    name: "Chrome Ratchet",
    ticker: "RATCH",
    image: "",
    banner: "",
    bannerGradient: "linear-gradient(135deg, #2d2d2d 0%, #4a4a4a 40%, #8b8b8b 100%)",
    marketCap: 1_120_000,
    floorValue: 92_400,
    liquidity: 445_000,
    change24h: 12.8,
    hooks: { antiSnipe: false, backedFloor: true, antiMev: false, customHook: false },
    address: "0x3b2C...8e2c",
    hookType: "Master",
  },
  {
    id: "3",
    name: "Void Runner",
    ticker: "VOID",
    image: "",
    banner: "",
    bannerGradient: "linear-gradient(135deg, #1a0533 0%, #4c1d95 50%, #7c3aed 100%)",
    marketCap: 680_000,
    floorValue: 41_200,
    liquidity: 220_000,
    change24h: -8.4,
    hooks: { antiSnipe: true, backedFloor: false, antiMev: true, customHook: true },
    address: "0x9d4e...3a1f",
    hookType: "Custom",
  },
  {
    id: "4",
    name: "Base Spark",
    ticker: "SPARK",
    image: "",
    banner: "",
    bannerGradient: "linear-gradient(135deg, #001a66 0%, #0052ff 55%, #d4ff00 100%)",
    marketCap: 3_800_000,
    floorValue: 312_000,
    liquidity: 1_200_000,
    change24h: 56.1,
    hooks: { antiSnipe: true, backedFloor: true, antiMev: true, customHook: false },
    address: "0x1a2b...9f0e",
    hookType: "Master",
  },
  {
    id: "5",
    name: "Liquid Hook",
    ticker: "HOOK",
    image: "",
    banner: "",
    bannerGradient: "linear-gradient(135deg, #0c4a6e 0%, #38bdf8 50%, #e0f2fe 100%)",
    marketCap: 920_000,
    floorValue: 78_500,
    liquidity: 380_000,
    change24h: 4.2,
    hooks: { antiSnipe: false, backedFloor: true, antiMev: false, customHook: false },
    address: "0x5e73...3408",
    hookType: "Master",
  },
  {
    id: "6",
    name: "Snipe Shield",
    ticker: "SHLD",
    image: "",
    banner: "",
    bannerGradient: "linear-gradient(135deg, #052e16 0%, #16a34a 50%, #bbf7d0 100%)",
    marketCap: 540_000,
    floorValue: 28_900,
    liquidity: 175_000,
    change24h: 18.7,
    hooks: { antiSnipe: true, backedFloor: false, antiMev: true, customHook: false },
    address: "0x8b5b...d3b9",
    hookType: "Master",
  },
  {
    id: "7",
    name: "Ponstar",
    ticker: "STAR",
    image: "",
    banner: "",
    bannerGradient: "linear-gradient(180deg, #7dd3fc 0%, #38bdf8 40%, #ffffff 100%)",
    marketCap: 2_100_000,
    floorValue: 156_000,
    liquidity: 620_000,
    change24h: 22.1,
    hooks: { antiSnipe: false, backedFloor: true, antiMev: false, customHook: false },
    address: "0xa1b2...c3d4",
    hookType: "Master",
  },
  {
    id: "8",
    name: "Meme Lord",
    ticker: "LORD",
    image: "",
    banner: "",
    bannerGradient: "linear-gradient(135deg, #450a0a 0%, #dc2626 50%, #fbbf24 100%)",
    marketCap: 890_000,
    floorValue: 12_400,
    liquidity: 98_000,
    change24h: -3.2,
    hooks: { antiSnipe: true, backedFloor: false, antiMev: false, customHook: true },
    address: "0xf00d...beef",
    hookType: "Custom",
  },
  {
    id: "9",
    name: "Floor Ratchet",
    ticker: "RATCH",
    image: "",
    banner: "",
    bannerGradient: "linear-gradient(135deg, #18181b 0%, #3f3f46 50%, #a1a1aa 100%)",
    marketCap: 1_450_000,
    floorValue: 198_000,
    liquidity: 520_000,
    change24h: 8.9,
    hooks: { antiSnipe: false, backedFloor: true, antiMev: true, customHook: false },
    address: "0xdead...cafe",
    hookType: "Master",
  },
];

export const NAV_LINKS = [
  { href: "/explore", label: "Explore" },
  { href: "/launch", label: "Create" },
  { href: "/floor", label: "Floor" },
  { href: "https://github.com", label: "Docs", external: true },
] as const;
