export const bondingFactoryAbi = [
  {
    type: "function",
    name: "launch",
    inputs: [
      {
        name: "params",
        type: "tuple",
        components: [
          { name: "name", type: "string" },
          { name: "symbol", type: "string" },
          { name: "metadataURI", type: "string" },
          { name: "totalSupply", type: "uint256" },
          { name: "quote", type: "address" },
          { name: "creatorTaxBps", type: "uint16" },
        ],
      },
    ],
    outputs: [
      { name: "launchId", type: "uint256" },
      { name: "token", type: "address" },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "buy",
    inputs: [
      { name: "launchId", type: "uint256" },
      { name: "quoteIn", type: "uint256" },
      { name: "minTokensOut", type: "uint256" },
    ],
    outputs: [
      { name: "tokensOut", type: "uint256" },
      { name: "feeQuote", type: "uint256" },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "sell",
    inputs: [
      { name: "launchId", type: "uint256" },
      { name: "tokensIn", type: "uint256" },
      { name: "minQuoteOut", type: "uint256" },
    ],
    outputs: [
      { name: "quoteOut", type: "uint256" },
      { name: "feeQuote", type: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "launchFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "launchCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "launches",
    inputs: [{ name: "launchId", type: "uint256" }],
    outputs: [
      { name: "token", type: "address" },
      { name: "creator", type: "address" },
      { name: "quote", type: "address" },
      { name: "phase", type: "uint8" },
      { name: "creatorTaxBps", type: "uint16" },
      { name: "totalSupply", type: "uint256" },
      { name: "curveSupply", type: "uint256" },
      { name: "tokensSold", type: "uint256" },
      { name: "realQuote", type: "uint256" },
      { name: "virtualQuote", type: "uint256" },
      { name: "virtualToken", type: "uint256" },
      { name: "graduationQuote", type: "uint256" },
      { name: "poolId", type: "bytes32" },
      { name: "launchedAt", type: "uint64" },
      { name: "graduatedAt", type: "uint64" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenLaunchId",
    inputs: [{ name: "token", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeHook",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "poolKeyOf",
    inputs: [{ name: "launchId", type: "uint256" }],
    outputs: [
      {
        name: "key",
        type: "tuple",
        components: [
          { name: "currency0", type: "address" },
          { name: "currency1", type: "address" },
          { name: "fee", type: "uint24" },
          { name: "tickSpacing", type: "int24" },
          { name: "hooks", type: "address" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "graduate",
    inputs: [{ name: "launchId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "TokenLaunched",
    inputs: [
      { name: "launchId", type: "uint256", indexed: true },
      { name: "token", type: "address", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "quote", type: "address", indexed: false },
      { name: "graduationQuote", type: "uint256", indexed: false },
    ],
  },
] as const;
