#!/usr/bin/env bash
# Build + restart Hookit on Linode (run after git pull).
# Usage: ./deploy/linode/deploy.sh   (as user hookit, from repo root)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

if [[ ! -f "${ROOT}/.env" ]]; then
  echo "Missing ${ROOT}/.env — copy deploy/linode/env.production.example" >&2
  exit 1
fi

# shellcheck disable=SC1091
set -a
source "${ROOT}/.env"
set +a

echo "[deploy] sync web env…"
WEB_ENV="${ROOT}/web/.env.production.local"
{
  echo "# generated by deploy/linode/deploy.sh — edit ${ROOT}/.env instead"
  grep -E '^(NEXT_PUBLIC_|INDEXER_URL|HOOKIT_REPO_ROOT|PINATA_)' "${ROOT}/.env" 2>/dev/null || true
  echo "HOOKIT_REPO_ROOT=${ROOT}"
} > "${WEB_ENV}"

echo "[deploy] indexer deps…"
cd "${ROOT}/indexer"
npm ci 2>/dev/null || npm install

echo "[deploy] forge build (custom hook API)…"
cd "${ROOT}"
forge build --quiet

echo "[deploy] web deps + build…"
cd "${ROOT}/web"
npm ci
npm run build

echo "[deploy] standalone assets…"
cp -r .next/static .next/standalone/.next/static
if [[ -d public ]]; then
  cp -r public .next/standalone/public
fi

mkdir -p "${INDEXER_DATA_DIR:-${ROOT}/indexer/data}"

if command -v systemctl >/dev/null 2>&1 && systemctl list-unit-files hookit-indexer.service &>/dev/null; then
  echo "[deploy] restart systemd services…"
  sudo systemctl restart hookit-indexer
  sudo systemctl restart hookit-web
  sudo systemctl status hookit-indexer hookit-web --no-pager || true
else
  echo "[deploy] no systemd — start manually:"
  echo "  cd ${ROOT}/indexer && npm run serve"
  echo "  cd ${ROOT}/web && HOOKIT_REPO_ROOT=${ROOT} node .next/standalone/server.js"
fi

echo "[deploy] smoke checks…"
sleep 2
curl -sf "http://127.0.0.1:${INDEXER_PORT:-8787}/health" | head -c 200 || echo "(indexer not up yet)"
echo
curl -sf -o /dev/null -w "web HTTP %{http_code}\n" "http://127.0.0.1:${PORT:-3000}/" || true

echo "[deploy] done."
